### PR TITLE
Allegro5 port

### PR DESCRIPTION
**Pull request by karjonas**
This is a port from allegro4 to allegro5. It contains quite a lot of changes that were necessary to achieve the upgrade.

Many functions are replaced by their allegro5 counterpart but some are implemented in the allegro_compatibilty.h file.

The main loop was rewritten since events are used for keyboard and joystick input.

The game should now be framerate-independent and use a delta time increment for the physics calculations.

I used the joystick code from https://github.com/dradtke/Allegro-360 to support the Xbox 360 joystick.

There is probably more details but these are the main ones. I have only tried this on win7 with msys2 and on linux. I only have one Xbox 360 controller so I have not tested with several joysticks connected.

### CODE REVIEW

**Comment by martinohanlon** [comment]
Thanks for the PR. Really really useful. I'm going away for 3 weeks tomorrow but I'll look into this as soon as I get back.

**Comment by martinohanlon** [comment]
Just out of interest what was your motivation to do the conversion. Is it a game you enjoy?

**Comment by karjonas** [comment]
I think it more or less just happened by chance. I stumbled upon it at freegamedev.net and tried it out. I had never heard of it before and not played the amiga version but I tried it and thought it was a nice game. I had previously tried porting another project from allegro4 to allegro5 and I saw that this game was using allegro4 and I thought that it would be a quite simple task to port it since it was not a very big game so I just started. As usual though I underestimated the work needed :) Hopefully using allegro5 can make the game work a bit further into the future too :)

**Comment by martinohanlon** [comment]
Just compiled on Windows.. Looking good so far. Ive noticed a couple of issues, which i will keep track of here.

**Comment by martinohanlon** [comment]
Issue - When ships crash debris doesnt appear in the top left.
mayhem2-debriserror

Edit - actually this is really weird... All the debris appears but its closer together
(shot from pre allegro5)
mayhem2-debriserror2

Its an error in itofix()
There is something wierd about itofix. The ships rotate slower now too.
This describes itofix() as setting the binary angle 64 which is 90 degrees
http://www1.udel.edu/CIS/software/dist/allegro-4.2.1/docs/html/alleg032.html#fixsin

Ah ok, allegro 4 used fixed point trigonometry:
http://www1.udel.edu/CIS/software/dist/allegro-4.2.1/docs/html/alleg032.html#Fixed point trig

Need to change to use allegro 5 fixed point maths.
https://www.allegro.cc/manual/5/fixed.html

Change allegro_compatability.cpp to provide mask to allegro 5 fixed point maths functions, i.e. 

```
al_fixed fixmul(al_fixed x, al_fixed y) {return al_fixmul(x, y); }
```

**Comment by martinohanlon** [comment]
Issue - Mouse pointer is left on the screen when playing the game

**Comment by martinohanlon** [comment]
Enhancement - bring this change into the code so the ships arent always in the middle of the screen.

https://github.com/martinohanlon/mayhem-pi/commit/231aee0111a3560e226cc87850ef74df65064423#diff-63857f1ef2458c748f693dee1fd2f394R433

**Comment by martinohanlon** [comment]
I have created a branch to the windows mayhem repo https://github.com/martinohanlon/mayhem/tree/allegro5 to manage this PR.

**Comment by karjonas** [comment]
Regarding the fixed point functions I think it is better to use real floating point math instead of the al_fixed type. It is simpler to debug and reason about real numbers which I think is more important than potential performance gains.  If we do that though we need to look closer at the trigonometric calls (fixsin,fixcos, et c.) since they use binary angles which we need to convert to degrees instead.

**Comment by martinohanlon** [comment]
I had come to a similar conclusion, I'm not sure if it's related to the move to real numbers but there are changes to the physics of the game e.g. debris travels much further, ships and bullets go faster, the ships fall slower.

Ive also noted a performance decrease, against the small netbook I use when I travel, previously it topped out 40+ fps, now its around 15 fps. I don't know how much of this is allegro 5 or other changes.

**Comment by karjonas** [comment]
Using real numbers will at least make a difference in the places using  the trig maths. It can also be an issue with using a delta increment instead of "tick-based" system. I tried getting the game to run at 40 fps but it was quite hard to make that happen since vsync prefers 30 or 60 fps. Also A5 has a slightly different idioms for handling events and such so a main loop that uses a delta increment seemed like the best way to handle different vsync issues. It also makes it possible to run at 60+ fps which is nice for smoothness. 

All performance issues I had were related in one or the other way to drawing or reading bitmaps. Putting pixels in bimaps in particular can be very expensive. I get 60 fps on my machines but they are much better than a netbook so I will try running it on my old netbook too. What OS are you running on btw?

Edit: I tested on a Asus 1001PX netbook with linux and it was able to run it close to 60 fps altough it was slightly erratic.

**Comment by martinohanlon** [comment]
That was running windows 10. What compiler are you using for windows? mingw32?

**Comment by martinohanlon** [comment]
I originally made loads of changes to get the game running well on windows.

**Comment by karjonas** [comment]
I see, I compiled on windows using msys2/mingw64. I also had some performance problems on windows when I used my dual boot computer with Win7 and Linux. But on linux I had no issues so I guess there is some performance problems specific to windows. We could try compiling using MSVC too. Otherwise the only way to find the bottleneck is to do some profiling on windows.

**Comment by martinohanlon** [comment]
Started looking at the allegro 5 port again now I am back.

I am quite often getting assertion failures:

```
  assert(frame >= 0 && frame < num_frames);
```

Any ideas?

**Comment by karjonas** [comment]
It is hard to say without a stack-trace but it has to do with an incorrect calculation of the frame that is used for the collision map. The reason I use a frame is because I calculate a collision map for rotated shapes of the ship to get a faster lookup instead of reading pixels from the bitmap. So the frame is actually more of an angle step counter.

**Comment by martinohanlon** [comment]
Ill try and get a stack trace for the error. 

Im still getting my head around some of the changes you have made, so I may ask some pretty simple question, number 1 being:

Im seeing through-out the changes:

```
* (dt / 0.025)
```

Now Im assuming this is so changes are calculates on the delta since last time but why 0.025 (40 fps??).

**Comment by karjonas** [comment]
Yes, it is based upon the fact that all the hardcoded increments assume a 40 fps tick. It is a bit misleading since you could instead just write

```
* (dt*40)
```

instead. But the proper thing I think is to multiply the actual constants with 40 beforehand and rename them accordingly like angle_per_sec or speed_per_sec.

**Comment by martinohanlon** [comment]
Here is the stack trace from the assertion error:

```
assert(frame >= 0 && frame < num_frames);
```

```
(gdb) bt full
#0  0x77718500 in msvcrt!_assert () from C:\WINDOWS\SysWOW64\msvcrt.dll
No symbol table info available.
#1  0x00404386 in test_collision (pv=0x2713b84, currentlevel=0x2713080)
    at collision.cpp:48
        frame = 51
        x_max = 0
        vaisseau = 0x270d7d0
        plt = 0x41706c <platforms1+108>
        test_it = true
        size = 31
        num_frames = 51
        y_max = 58657919
#2  0x0040bf90 in mega_collision_test (allpi=0x2713b04, views=0x2713b84,
    vaisseaux=0x270d7d0, currentlevel=0x2713080, nbplayers=2,
    nombre_vaisseau=2) at player_view.cpp:413
        dca = 0x27130b8
        i = 0
        j = 40955320
#3  0x00403879 in BattleSequence::doTick (this=0x270d7a8,
    screen_buffer=0x26622d0, key_pressed=0x65fca5, key_down=0x65fd88,
    exit_game=0x65fe6b, dt=0.021471918681861268) at battle_sequence.cpp:434
        i = 2
#4  0x00405cad in GameManager::Run (aSeq=0x270d7a8) at game_mgr.cpp:197
        ev = {type = 11, any = {type = 11,
            source = 0x673e9a60 <the_keyboard>,
            timestamp = 50.996551063816113}, display = {type = 11,
            source = 0x673e9a60 <the_keyboard>,
            timestamp = 50.996551063816113, x = 40175936, y = 24,
            width = 120, height = 512, orientation = 67133696}, joystick = {
            type = 11, source = 0x673e9a60 <the_keyboard>,
            timestamp = 50.996551063816113, id = 0x2650940, stick = 24,
            axis = 120, pos = 7.17464814e-043, button = 67133696},
          keyboard = {type = 11, source = 0x673e9a60 <the_keyboard>,
            timestamp = 50.996551063816113, display = 0x2650940,
            keycode = 24, unichar = 120, modifiers = 512, repeat = false},
          mouse = {type = 11, source = 0x673e9a60 <the_keyboard>,
            timestamp = 50.996551063816113, display = 0x2650940, x = 24,
            y = 120, z = 512, w = 67133696, dx = 318, dy = 1893618,
            dz = 1893618, dw = 35, button = 318, pressure = 5.60519386e-045},
          timer = {type = 11, source = 0x673e9a60 <the_keyboard>,
            timestamp = 50.996551063816113, count = 103119391040,
            error = 1.0864618450335073e-311}, touch = {type = 11,
            source = 0x673e9a60 <the_keyboard>,
            timestamp = 50.996551063816113, display = 0x2650940, id = 24,
            x = 1.68155816e-043, y = 7.17464814e-043, dx = 1.50908679e-036,
            dy = 4.45612912e-043, primary = 242}, user = {type = 11,
            source = 0x673e9a60 <the_keyboard>,
            timestamp = 50.996551063816113,
            __internal(double,...)(short, char, long double) = 0x2650940,
            data1 = 24, data2 = 120, data3 = 512, data4 = 67133696}}
        now = 51.14943390271835
        do_tick = true
        screen_buffer = 0x26622d0
        key_down = {false <repeats 24 times>, true, false <repeats 202 times>}
        exit_game = false
        delta_min = 0.015384615384615385
        event_queue = 0x26620b8
        key_pressed = {false <repeats 227 times>}
        doexit = false
        seq_next = 0x0
        last_time = 51.127961984036489
#5  0x004091f0 in main () at Mayhem2.cpp:40
        seq = 0x2661b18
```

**Comment by karjonas** [comment]
This is strange, num_frames should be 72 in the case of the collision map for the ship. The number of frames is set in the init method of the collision map and is set at vaisseau_data.cpp:71

```
  int num_frames = 360 / VAISSEAU_ANGLESTEP;
```

where VAISSEAU_ANGLESTEP = 5 which should make num_frames = 72. This should be changed to

```
 int num_frames = 360 / anglestep;
```

though since that is the actual input argument. You should also make sure that init_vaisseau_data returns zero and not --1 even if this is not likely the issue. I think the key point is to make sure that the collision map is created properly for the ship. I do not know what is the issue other than that.

**Comment by martinohanlon** [comment]
Ok, so perhaps this is making more sense, due to the changes relating to angles i have changed to the angle step (to 7 I think) as the ship was rotating too slowly.

**Comment by martinohanlon** [comment]
Hi @karjonas Im just doing some joystick tesing, when I use an xbox 360 controller I get different button values to the ones in xc.c (https://github.com/dradtke/Allegro-360/blob/master/src/xc.c) - e.g. The left and right shoulder buttons are opposite - did you test a controller? I dont know if its a specific issues to my setup or the code is simply out of date.

**Comment by karjonas** [comment]
I tried it now on Linux and they are correct for me. What OS did you try?

**Comment by martinohanlon** [comment]
This was windows 10. When I use al_get_joystick_name() the controller
describes itself as an XInput Joystick.

I think I'll add some config to manage different configs by joystick name.

**Comment by karjonas** [comment]
I tried this on Win10 and the mapping is wrong there for me too. On Linux the joystick name is 'Microsoft X-Box 360 pad' so it is indeed platform dependent.

**Comment by martinohanlon** [comment]
Thanks for checking. I've made some changes to allow for different joystick
maps based on joystick name so it should be ok.

**Comment by martinohanlon** [comment]
I've just compiled this onto a Raspberry Pi 3. There is a serious problem with performance, opening up the game results in draw_fps of 1 fps and tick ms of > than 300ms. If I comment out the aSeq->doTick, tick_ms drops to 1.2ms but draw_fps stays around 1 fps.

Before I start hacking with the code have you got any thoughts?

**Comment by karjonas** [comment]
Well, if it is not the event queue then it is some real problem with the graphics since we are only clearing a bitmap and drawing it to the screen. Can you try one of the simple allegro5 bitmap examples in their wiki and see if they work correctly?

**Comment by martinohanlon** [comment]
I put some debug timers into the game mgr. I think I have narrowed down the problem to it taking between 600ms & 1200ms to do:

    al_flip_display();

The only thing it was writing to the screen was the screen res and the fps counter - I commented out everything else.

When running this, its also pushing the CPU to 95%!

**Comment by karjonas** [comment]
It might be some strange issue with the vsync limiting performance. You could try disabling vsync. I have the older RPi model so I will try it out on that one later this week.

**Comment by martinohanlon** [comment]
I had the same thoughts re vsync and that's the first thing on my list to
try.

**Comment by martinohanlon** [comment]
So, ive been doing a bit more investigation. The function which is really slow is drawing bitmaps.

If you write directly to the display `al_flip_display()` really fast, if you write to screen_buffer and then use `al_draw_bitmap()` to draw this to the display, when `al_flip_display()` is called it is really slow.

Modify VSYNC settings didnt make any difference `al_set_new_display_option(ALLEGRO_VSYNC, 2, ALLEGRO_REQUIRE);`

**Comment by karjonas** [comment]
The screen_buffer bitmap is superfluous so I created a pull request where I removed it and instead use the back buffer directly.

**Comment by martinohanlon** [comment]
Before I do anything else im going to compile the latest version of allegro on the Pi. I'm currently using the version from the repo.

**Comment by martinohanlon** [comment]
Updated allegro to 5.2.1 and got the same results.

Ignore that... Didnt recompile. Duh!

**Comment by martinohanlon** [comment]
I need to do some more testing, but I think I have worked out the problem...

Not enough graphics memory!  When set to the default of 64MB, it is very slow, set to 128MB its fine! Presumably the performance problems are due to it having to swap bitmaps between video and system memory.

**Comment by martinohanlon** [comment]
So, Ive done some more investigation. It looks like allegro isn't clearing video memory, using

`sudo vcdbg reloc`

I can see the graphics memory allocation, each time you start a game (i.e. from the intro screen) the memory usage increases, but when you exit a level it doesnt clear down the memory. So even after increasing memory allocation, by entering and exiting a number of levels, free memory will reduce to zero.

Only after exiting the game is the memory cleared.

**Comment by martinohanlon** [comment]
Ah ha...  Im pretty sure the class de-constructor's aren't being called and resources arent being cleared up.

```
BattleSequence::~BattleSequence() {
  printf("end off class\n");
```

This doesn't get called.

**Comment by martinohanlon** [comment]
@karjonas Im pretty sure this is the changes you made in `game_mgr.cpp` to delete the return screen and therefore invoke the deconstructor.

```
if (seq_next != iReturnScreen && iReturnScreen) {
        printf(" delete return screen\n");
        delete iReturnScreen;
      }
```

I dont think its running. Or I certainly never see the debug message.

**Comment by karjonas** [comment]
The logic was indeed incorrect but when I fixed it it resulted in some other issues so I created a pull request for it https://github.com/martinohanlon/mayhem/pull/13

**Comment by martinohanlon** [comment]
I've just merged the allegro5 branch into dev. :)

**Comment by karjonas** [comment]
Excellent :) 👍

**Comment by martinohanlon** [comment]
I've just merged the allegro 5 port into master!

Thank you very much for your contribution, long may it continue :)  This puts us on the right foot for Mayhem to have greater longevity.

Its been interesting getting this PR ready for release, lots of little changes here and there to get it all working across both PC & Pi, but great fun.

**Pull request closed without merging**
